import UserCard from "../cards/UserCard";
import { Button } from "@acme/ui";
import { HomeIcon } from "lucide-react";
import Head from "next/head";
import Link from "next/link";

export interface IPrimaryLayout extends React.ComponentPropsWithoutRef<"div"> {
  title?: string;
  description?: string;
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({
  children,
  title = "Create T3 App",
  description = "Generated by create-t3-app",
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <Button
          className="hover:text-white fixed left-0 top-0"
          variant="link"
          asChild
        >
          <Link href="/">
            <HomeIcon />
          </Link>
        </Button>

        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-8">
          <UserCard />

          {children}
        </div>
      </main>
    </>
  );
};

export default PrimaryLayout;
