import UserCard from "../cards/UserCard";
import Head from "next/head";

export interface IPrimaryLayout extends React.ComponentPropsWithoutRef<"div"> {
  title?: string;
  description?: string;
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({
  children,
  title = "Create T3 App",
  description = "Generated by create-t3-app",
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-8">
          <UserCard />

          {children}
        </div>
      </main>
    </>
  );
};

export default PrimaryLayout;
